### ISSUE TITLE
Data resource

### ISSUE THREAD

**Issue by maggielee1111** [olegursu/drugtarget#1]
Hi Dr. Ursu!
I am trying to get the most updated version of this repository in Drug Central. Could you help me recalling if you download all these tsv files from [download website](https://drugcentral.org/download) or did you transform and map the data based on the Drug Central sql data [Download Database dump 05/10/2023](https://drugcentral.org/ActiveDownload)?
Since the only tsv format data I saw is [Download](https://unmtid-shinyapps.net/download/DrugCentral/2021_09_01/drug.target.interaction.tsv.gz)... Thank you for any help!

**Comment by olegursu** [comment]
Hi Manqi 

You will need to download the database dump and load it into a Postgres instance, I used a script to generate the TSV files, since I am not the current maintainer of DrugCentral anymore I suggest to contact Sorin Avram, his ORCHID id is here https://orcid.org/0000-0002-4816-7446 email: sorin_avram@acad-icht.tm.edu.ro for help with getting an up to date version of the files.
